import Head from 'next/head';
import styles from '@/styles/components/sections/Home.module.scss';
import HomeSection from '@/components/sections/home';
import AboutSection from '@/components/sections/about';
import EducationSection from '@/components/sections/education';
import ExperienceSection from '@/components/sections/experience';
import ProjectsSection from '@/components/sections/projects';
import ContactSection from '@/components/sections/contact';

export default function Home() {
  return (
    <>
      <Head>
        <title>Pavaruth&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/me.jpeg" />
      </Head>
      <>
        <section id="home" className="min-vh-100 d-flex align-items-center">
          <HomeSection />
        </section>
        <section
          id="about"
          className={`min-vh-100 d-flex align-items-center ${styles.secPad}`}
        >
          <AboutSection />
        </section>
        <section
          id="education"
          className={`min-vh-100 d-flex align-items-center ${styles.secPad}`}
        >
          <EducationSection />
        </section>
        <section
          id="experience"
          className={`min-vh-100 d-flex align-items-center ${styles.secPad}`}
        >
          <ExperienceSection />
        </section>
        <section
          id="projects"
          className={`min-vh-100 d-flex align-items-center ${styles.secPad}`}
        >
          <ProjectsSection />
        </section>
        <section
          id="contact"
          className={`d-flex align-items-center ${styles.secPad}`}
        >
          <ContactSection />
        </section>
      </>
    </>
  );
}
