import Head from 'next/head';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.scss';
import HomeSection from '@/components/home';
import AboutSection from '@/components/about';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Pavaruth B</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <section className='min-vh-100 d-flex align-items-center'>
          <HomeSection />
        </section>
        <section className='min-vh-100 d-flex align-items-center'>
          <AboutSection />
        </section>
      </>
    </>
  );
}
