import Head from 'next/head';
import styles from '@/styles/Home.module.scss';
import HomeSection from '@/components/sections/home';
import AboutSection from '@/components/sections/about';
import EducationSection from '@/components/sections/education';

export default function Home() {
  return (
    <>
      <Head>
        <title>Pavaruth Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <section id="home" className="min-vh-100 d-flex align-items-center">
          <HomeSection />
        </section>
        <section
          id="about"
          className={`min-vh-100 d-flex align-items-center ${styles.secPad}`}
        >
          <AboutSection />
        </section>
        <section
          id="education"
          className={`min-vh-100 d-flex align-items-center ${styles.secPad}`}
        >
          <EducationSection />
        </section>
      </>
    </>
  );
}
